<?php

return [
    'name' => '嵩县金融服务系统',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' => [
        'backend' => 'zh-cn',
        'frontend' => 'zh-cn',
    ],
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'page' => 'Page',
        'article' => 'Article',
        'test' => 'Test',
    ],
    'configgroup' => [
        'bigscreenconfig' => '大屏数据设置',
        'basic' => 'Basic',
        'dictionary' => 'Dictionary',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'poor_count' => '0',
    'creditcountry' => '',
    'creditvillage' => '',
    'compensation' => '0',
    'collectionprice' => '0',
    'violationprice' => '0',
    'coupling' => [
        '龙头企业带动 每个产业' => '3个',
        '农民专业合作社 全县' => '6个',
        '农户参与 每户产业' => '5个',
        '产业基地总数 全县' => '2个',
        '带动贫困户参与 带动贫困户' => '5000万户',
    ],
    'leading' => [
        '林' => '23',
        '药' => '541',
        '烟' => '55',
        '牡' => '24',
        '茵' => '854',
        '旅游' => '551',
    ],
    'layoutplan' => [
        '南部片区' => '车村镇主要以中药材、食用菌（夏香菇）和旅游服务业为主；白河镇主要以食用菌、山茱萸、中华蜂以及旅游服务业为主；木植街乡主要以食用菌、山茱萸为主。',
        '北部片区' => '田湖镇主要以中药材、烟叶和葡萄等特色种植为主；闫庄主要以黄牛、奶山羊养殖和烟叶、大葱、花生为主；大坪乡主要以油菜、玫瑰、中药材和生猪养殖为主；库区乡主要以中药材和辣椒、猕猴桃等特色种植业为主。',
        '东部片区' => '黄庄乡主要以食用菌、花椒、红薯种植为主；九皋镇主要以皂角、脱毒红薯和旅游服务业为主；饭坡镇主要以中药材和软籽石榴为主；纸坊镇主要以中药材、特色产业、蚕桑种植为主。',
        '西部片区' => '城关镇主要以食用菌和中药材、蔬菜大棚为主；何村乡主要以中药材种植（柴胡）、食用菌和中华蜂养殖为主；德亭镇主要以中药材、特色产业和羊肚菌种植和旅游服务业为主；大章镇主要以红油香椿和中药材种植为主。',
    ],
];
